### ISSUE TITLE
Create some material on power and energy

### ISSUE THREAD

**Issue by moorepants** [moorepants/learn-multibody-dynamics#108]
I ended up dropping material on energy and power, but this is too important to leave out. Checking the energy state for conservation in simulation and also understanding how to properly calculate power are a couple of critical pieces students will need in their future work.

**Comment by Peter230655** [comment]
Looking at the total energy has helped me many times to correct my description of the system I was setting up. (The latest one being the v2pt_theory issue. Only because the total energy refused to be constant did I finally come up with a solution)
Maybe a hint to this effect would be useful?

**Comment by moorepants** [comment]
Yes, that should definitely be included.

**Comment by moorepants** [comment]
Energy chapter is in, but I didn't include what I hoped about power, i.e. power in and out of a system and the exchange vs time.

**Comment by moorepants** [comment]
Calling this complete. Can consider more on power at a later date.
