### ISSUE TITLE
Representations of orientations

### ISSUE THREAD

**Issue by wwolfie** [moorepants/learn-multibody-dynamics#118]
The chapter on orientation of reference frames introduces three representations of orientation:

1. Direction cosine matrix
2. Axis-angle (via the orient-axis method in sympy)
3. Euler-angles

It is not made explicit that these are (in some sense) three alternatives, with different pros and cons. A brief section at the end could make this explicit, and discuss the pros and cons.

In such a section, quaternions could be introduced in one sentence (via their transformation to axis-angle representation). Which allows to explain why Euler angles are used in the rest of the material, and to refer out to materials on Quaternions (or even some material on Lie-groups).

There is a downside of adding such a section at this point in the text: the readers don't yet know about angular velocity at this points, and some (most) of the pros and cons of the representations involve their rates of change and how that relates to angular velocity.

**Comment by moorepants** [comment]
I like this suggestion.

**Comment by wwolfie** [comment]
#130

**Comment by wwolfie** [comment]
There is now a PR for this #130, but I have no permission to link it.
