### ISSUE TITLE
Euler angle animation from wikipedia has incorrect coloring

### ISSUE THREAD

**Issue by moorepants** [moorepants/learn-multibody-dynamics#136]
I'm fairly certain that this animation:
![](https://upload.wikimedia.org/wikipedia/commons/8/85/Euler2a.gif)
is slightly off. The lower yellow arrow in the animation should be green, considering that common colored arrows should be orthogonal.

A new figure is needed.

**Comment by wwolfie** [comment]
Any feedback?

The order of the colors, so the rotations are in RGB order, could make the initial one black or gray.

The rendering struggles a bit with plotting the same size arrow on top of eachother, mixing the colors. I think in this case the effect is quite useful, but of course I can also (slightly) shrink arrowsizes to make one color dominant. 

![out](https://user-images.githubusercontent.com/24700070/222403993-99af836d-148e-478f-8fff-08bad6c9766d.gif)

**Comment by moorepants** [comment]
That's great! I like it better than the wikipedia one because it is correct. The overlapping colors is ok. How did you draw it? Wondering how we will commit this? (binary or code that generates it)

**Comment by moorepants** [comment]
You should also submit to Wikipedia to overwrite theirs :)

**Comment by wwolfie** [comment]
This was made with [Makie.jl]( https://docs.makie.org/stable/), using the GLMakie back-end. 

It might be possible to use the WGLMakie back-end to add the generated plotting code to the website directly, but probably easier to just commit the binary output for viewing. 

What is the best place to store the Julia code?

**Comment by moorepants** [comment]
> It might be possible to use the WGLMakie back-end to add the generated plotting code to the website directly, but probably easier to just commit the binary output for viewing.

My current process for this is to store binary assets in an object store that I own, I generally try not to commit binary assets to git.

> What is the best place to store the Julia code?

You can add it here if you'd like. Maybe we should have a `bin/` that has helper scripts for the repo. This repo is of course not setup for Julia dependencies, so maybe just uploading a script for now is fine. I'm not sure I want to complicate the build process for a single Julia script. You could also just put it in a gist or even just a paste into this issue in case we need to generate it again.
