### ISSUE TITLE
Question about vector notation in course materials

### ISSUE THREAD

**Issue by lazarjov** [moorepants/learn-multibody-dynamics#142]
Hey there,

I have a very minor question: why is the vector notation in course materials with the bar, instead of the arrow?

Thanks,
Lazar

**Comment by moorepants** [comment]
Because that is what I use to indicate a vector.

**Comment by moorepants** [comment]
This is a duplicate of https://github.com/moorepants/learn-multibody-dynamics/issues/92, so I'll close it. More info is there.
