### ISSUE TITLE
Correction Orientation.rst

### ISSUE THREAD

**Issue by jtheinen** [moorepants/learn-multibody-dynamics#15]
## Simple Rotations
- line 110: Shouldn't the signs of the sin(theta) be switched in a rotation matrix generally?
- line 120: Maybe it's valuable to say that A_C_N maps values from frame N to frame A

## Direction Cosine Matrix
- line 259: Note that A_C_N is the same as found in Simple Rotations but with a different method

## Gimbal and Euler angles
- line 626 Maybe explicitly say where the 12 valid sets of successive rotations come from (4 frames 3 axis)

**Comment by moorepants** [comment]
> line 110: Shouldn't the signs of the sin(theta) be switched in a rotation matrix generally?

I don't think so. Can you give an example of what you think is the correct way?

>  line 626 Maybe explicitly say where the 12 valid sets of successive rotations come from (4 frames 3 axis)

I'm not sure that 4 frames and 3 axes is sufficient condition for determining that there are only 12 possible successive rotations. Can you point me to a reference that explains that?

**Comment by moorepants** [comment]
These people just define it differently than I do. My notation is what I've written in the notes. They happen to use a different notation and are showing the transpose of what I'm showing.
