### ISSUE TITLE
Minor error in Vector equation (34)

### ISSUE THREAD

**Issue by SuperJappie08** [moorepants/learn-multibody-dynamics#170]
Hi,

While reading the book, I found a minor mistake in equation (34) of the vectors chapter ([link](https://moorepants.github.io/learn-multibody-dynamics/vectors.html#vector-functions)).

It states the following: $$\bar{v} = v_x \hat{a}_x + v_y \hat{a}_y + v_y \hat{a}_y$$

It probably was supposed to be: $$\bar{v} = v_x \hat{a}_x + v_y \hat{a}_y + v_z \hat{a}_z$$

(It has a double $y$ component and was missing a $z$ component)

Here is the [link to the source line associated with the equation](https://github.com/moorepants/learn-multibody-dynamics/blame/d86f82eeddc96814268f93d3ada72005ed73cc31/vectors.rst#L134)

**Comment by moorepants** [comment]
Thanks. Fixed in 905ad54.
