### ISSUE TITLE
Why the complexity of mixed and matched basis formulas?

### ISSUE THREAD

**Issue by whodidwhat** [moorepants/learn-multibody-dynamics#186]
I've been reading the Hodges version of the Kane's Method book and using your text as a companion to learn sympy. To be honest I find the use of the mixed and matched basis formulas unnecessarily confusing. You can always just express the vector in the basis of interest and differentiate normally, since the basis vectors are fixed. The mixed/matched formulas are accounting for the derivatives of the basis vectors when they are changing with respect to the basis you want. These days you have a computer and here sympy, why not use it and avoid the complexity and confusion of trying to express vectors in different bases....

**Comment by moorepants** [comment]
You'll have to be much more precise in your writing for me to understand what you are suggesting or asking.

**Comment by moorepants** [comment]
Closing due to lack of information. Reopen if you want to explain more.
