### ISSUE TITLE
Angular Kinematics

### ISSUE THREAD

**Issue by Peter230655** [moorepants/learn-multibody-dynamics#36]
1.
I think, the steps from eq(39) to eqs (40), (41), (43) are possible because one can pull factors out of the cross product as mentioned earlier in the lecture. This is called _bilinearity_, I think (?).  

2.
I find eq(43) intuitively very clear:
If a rigid body is fixed to frame B, and some ant is walking on it, the speed of the ant relative to frame A is the speed of the ant relative to frame B ( B_du/dt ) plus the speed  of the point the ant is at time t relative to frame A ( A_omega_B x u ). This somehow seems 'obvious' to me.

3.
It seems to me, that calculating angular accelerations is best left to sympy.physics.mechanics. Even the simple example given would be difficult to calculate manually.

**Comment by moorepants** [comment]
> It seems to me, that calculating angular accelerations is best left to sympy.physics.mechanics. Even the simple example given would be difficult to calculate manually.

Totally!

**Comment by moorepants** [comment]
No changes made regarding these comments, closing.
