### ISSUE TITLE
Translational Kinematics

### ISSUE THREAD

**Issue by Peter230655** [moorepants/learn-multibody-dynamics#39]
1.
Below Fig 21 your designation
r_P_S
means a vector starting at P and ending at S

_Write out the position vectors to 𝑃
P
, 𝑆
S
, and 𝑄
Q
:

h, d, w, c, l = sm.symbols('h, d, w, c, l')

r_O_P = h*N.z
r_P_S = -d*A.x
r_S_Q = -w*B.x - (c + l/2)*B.z

r_O_P, r_P_S, r_S_Q
_

Further down in the lecture, below eq(55), you define:
_r_R_S = R.pos_from(S)_
To be consistent with the above designation, should this not be called r_S_R ?

2.
Right above the Velocity Two Point Theorem is says:

_Also, once the position vectors are established, velocities can be calculated. You will always explicitly need to set the velocity of at least one point.
_
An explanation of this obvious fact may be that sympy.physics.mechanics has no way of knowing whether the sculpture is fixed on the road or floating around with some constant speed. All the relative speeds would not be changed by this. Hence at least the speed of one point must be fixed.

3.
Playing around with my useless programs, the
_v2pt_theory_ 
was a great step!
Before I understood it, I often made mistakes in determining the speed of some point.
So, at least for me, this theorem was a great help to make my useless programs at least right!

The last equation shows, that manually calculating the acceleration of the bird relative to N is almost hopeless.
( Would the equation not still look more forbidding, if it was expressed in N, rather than in a 'mixture' of A and B ?)

**Comment by Peter230655** [comment]
I tried to express the last equation, the acceleration of the bird in N, by adding _.express(N)_.
As expected the term becomes even more forbidding.

**Comment by moorepants** [comment]
> Below Fig 21 your designation `r_P_S` means a vector starting at P and ending at S

Here is the notation that I should be using:
![image](https://user-images.githubusercontent.com/276007/156927799-0952253e-47cc-4008-9605-979cc159b37b.png)

So ` r_R_S = R.pos_from(S)` should be ` r_S_R = R.pos_from(S)`.

Fixed.

**Comment by moorepants** [comment]
> An explanation of this obvious fact may be that sympy.physics.mechanics has no way of knowing whether the sculpture is fixed on the road or floating around with some constant speed. All the relative speeds would not be changed by this. Hence at least the speed of one point must be fixed.

I added a note with very similar text to what you write here.

**Comment by moorepants** [comment]
> Playing around with my useless programs, the `v2pt_theory` was a great step!

Yes. It is my most used comment for velocity calculations.
