### ISSUE TITLE
Mass distribution

### ISSUE THREAD

**Issue by jtheinen** [moorepants/learn-multibody-dynamics#55]
line 326: show -> shown

line 638: not completely clear, are 'the line' and 'the inertia vector' the same in this sentence? And can the principal plane be at any point on this line?

line 591: maybe add before this sentence: When calculating the inertia about an arbitrary point O, you have to account for the distance from the centre of mass to point O. This is done with the parallel axis theorem

line 603:  Previously you said U is non commutative, in Kane the U is before the r, in your formula U is after r

When providing examples during the lecture, the text will be understandable!

**Comment by moorepants** [comment]
> line 603: Previously you said U is non commutative, in Kane the U is before the r, in your formula U is after r

For this, I need to make a notation that shows U is the unit dyadic, not just a general dyadic. I need to think of the symbol to use.

**Comment by moorepants** [comment]
> not completely clear, are 'the line' and 'the inertia vector' the same in this sentence?

No they aren't. A vector is not bound to a line or point. I use the word line here because an axis = line. And axis isn't really the same as a vector.

**Comment by moorepants** [comment]
> line 638: not completely clear, are 'the line' and 'the inertia vector' the same in this sentence? And can the principal plane be at any point on this line?

I didn't think of something to clarify this. I'm not saying more there because I shouldn't need to. A vector != line and a plane doesn't have to be associated with a point.

**Comment by moorepants** [comment]
> line 591: maybe add before this sentence: When calculating the inertia about an arbitrary point O, you have to account for the distance from the centre of mass to point O. This is done with the parallel axis theorem

Added something similar.

> line 603: Previously you said U is non commutative, in Kane the U is before the r, in your formula U is after r

Clarified the earlier statement on what is commutative and what isn't. If U is the unit dyadic then it is commutative.
