### ISSUE TITLE
Need explanation on the points on a rolling wheel

### ISSUE THREAD

**Issue by moorepants** [moorepants/learn-multibody-dynamics#56]
The idea that you can select the point that is always at the contact location but it fixed on the disk, is complex. A student asked about it. It needs a little video explaining it.

**Comment by Peter230655** [comment]
As I see this issue:
As seen from the street's and from the wheel's point of view, the contact point is a 'new' point at each new time instance. This new point is at rest relative to the street, but gone and replaced by a new point an instance later.
So, the life time of the contact point is only an instance long, but it is at rest during it's infinitesimally short live.

No idea, whether this helps understanding the issue - at least it helped me.

**Comment by Peter230655** [comment]
I wrote a small program to model a wheel running down an uneven street, using exactly this fixed contact point. Results seem to look as one would expect.

**Comment by moorepants** [comment]
> but gone and replaced by a new point an instance later

I like this for sure. I'll use some of your wording when I write it.

**Comment by moorepants** [comment]
I added this in the 2023 update to the nonholonomic chapter.

**Comment by Peter230655** [comment]
When the ellipse is rotated from 0 to $q$, the arc length is $\int_{0}^{q(t)} \sqrt{a^2sin(k)^2 + b^2cos(k)^2}\,dk \ $.

The arc length of a function f(k(t)) from 0 to $x(t)$ is: $ \int_{0}^{x(t)} \sqrt{1 +  \left(\frac{d}{dx}(f(k(t))\right) ^2} \,dk \ $ (I found all this in the internet)
