### ISSUE TITLE
Why did you ignore q5 in the lamp exercise (vectors)?

### ISSUE THREAD

**Issue by tamoora** [moorepants/learn-multibody-dynamics#60]
I was going through the example and trying to write the code myself, but I noticed that your solution ignored q5. I also see you defined C relative to B as: `C.orient_body_fixed(B, (q3, q4, 0), 'XZX')` I thought this should be `C.orient_body_fixed(B, (q4, q5, 0), 'XZX')`

Is this a mistake or did I misunderstand something?

Thanks for the awesome course by the way!

**Comment by engineertee** [comment]
Sounds good, I can take a stab at fixing it and create a pull request if you can confirm it's a mistake.

**Comment by moorepants** [comment]
Yes it is a mistake. You have the correct statement where q4 and q5 are used instead of q3 and q4. Nice catch! If you want to make a pull request. I'll accept it.
