### ISSUE TITLE
sphinx-autobuild becomes slow

### ISSUE THREAD

**Issue by moorepants** [moorepants/learn-multibody-dynamics#82]
In general, the sphinx caching mechanism works well with sphinx-autobuild but if an error occurs in a `jupyter-execute` cell on a build, then the cache seems to be invalidated causing all of the pages to be rebuilt. This makes the edit review cycle too slow once many rst files that each take a long time to compute are present.

**Comment by moorepants** [comment]
I tried to speed up local builds using the only directive but it didn't seem to prevent the execution of the code in the only directive when not a draft. Here is the revert:

https://github.com/moorepants/learn-multibody-dynamics/commit/66ed3998f8881a750c86715bf1ddc2cee3798f02

**Comment by moorepants** [comment]
The matplotlib `to_jshtml()` calls take a lot of time.

**Comment by Peter230655** [comment]
You mean for animations?
I need this on my iPad, or is it Jupyter Notes? for animations, and it is terribly slow!!

**Comment by moorepants** [comment]
This issue has to do with sphinx and jupyter-sphinx, which you are presumably not using.

**Comment by moorepants** [comment]
I opened this issue on jupyter-sphinx: https://github.com/jupyter/jupyter-sphinx/issues/219

**Comment by moorepants** [comment]
> The matplotlib to_jshtml() calls take a lot of time.

One way to probably reduce the time of these calls is to down sample the simulation data to the frames per second desired, then pass to the animation. The animation probably generates an image for every time stamp and then down samples before displaying to get the right frames per second.

**Comment by Peter230655** [comment]
No, I definitely do not use this! :-)

**Comment by moorepants** [comment]
I tried setting the frame format on the writer directly to see if it would produce an svg (and maybe be faster) for animations but it seems to still generate pngs. I think the only way to speed up the animation generation from matplotlib is to reduce frames per second or reduce duration. For the 10 second nonholonomic animation, going to 10 fps makes it choppy, but 20 is fine. Here was the writer code:

```python
#HTML(ani.to_jshtml(fps=fps))
from pathlib import Path
from matplotlib.animation import HTMLWriter

path = Path("temp.html")
writer = HTMLWriter(fps=fps,
                    embed_frames=True)
writer.frame_format = 'png'
ani.save(str(path), writer=writer)
HTML(path.read_text())
```

**Comment by moorepants** [comment]
I've added a new way to just run builds for a single chapter using an environment variable here: b9f119d03df21f902993edf719836767bc9c5320 This makes building much faster and solves the issue for me iterating locally on the books.

**Comment by moorepants** [comment]
I've opened the issue on jupyter-sphinx and have a local workaround, so closing this.
