### ISSUE TITLE
Terminology Consistency: `this course` versus `these materials`

### ISSUE THREAD

**Issue by agryman** [moorepants/learn-multibody-dynamics#93]
Another small point but possibly worth resolving. In general, a course may have other materials. Sometimes the book refers to `this course`. Sometimes the text refers to `these materials`. Is it refering to something in addition to the book? It might be simpler to uniformly refer to `this course` which is inclusive of everything.

**Comment by moorepants** [comment]
I think that I'd like to remove the instances of "this course" in favor of "these materials". I also may have written "this book" or "this website". I was struggling whether I should call it a book, a website, or materials. I do want the primary chapters to be tied to the lessons we complete in the course and then some appendices for extra topics. Ideally I keep the course specific things on the course website and these materials can standalone.

**Comment by agryman** [comment]
I change "this course" to "these materials" going forward.

**Comment by moorepants** [comment]
I'm changing things to "book".
