### ISSUE TITLE
Create chapter that demonstrates Lagrange's approach to constrained systems

### ISSUE THREAD

**Issue by moorepants** [moorepants/learn-multibody-dynamics#96]
We've agreed to add this as a lesson in the 2023 course, so we need a chapter to go along with it. Probably should go after the DAE simulation chapter so that we can apply the DAE integrator to this system.

**Comment by wwolfie** [comment]
Linking the (currently draft)  pull request: 

https://github.com/moorepants/learn-multibody-dynamics/pull/140

**Comment by moorepants** [comment]
Done!
